#!/bin/sh /etc/rc.common

START=55
STOP=55

export EXTRA_HELP=" status  Status of the service"
export EXTRA_COMMANDS="status"

export PROCLINE="/opt/filetunnel/stunserver --verbosity 1"
export PROCFLAG=$PROCLINE
export PROC_DEBUG_FLAG="on"
export OOM_FLAG=0

export EXTRA_HELP=" status  Status the service"
export EXTRA_COMMANDS="status"

stop() {
  /usr/sbin/supervisord stop
  return $?
}

start() {
  /usr/sbin/supervisord start
  return $?
}

restart() {
  stop
  sleep 1
  start
  return $?
}

shutdown() {
  stop
  return $?
}

status() {
  /usr/sbin/supervisord status
  return $?
}
