#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

#01 is fstab
START=02

SERVICE_USE_PID=1

start() {
	[ -f /etc/syslog-ng.conf ] || return 1
	service_start /usr/sbin/syslog-ng
	return $?
}

stop() {
	service_stop /usr/sbin/syslog-ng
}

reload() {
	service_reload /usr/sbin/syslog-ng
}
