#!/bin/sh /etc/rc.common

START=11

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	service_start /sbin/ubusd
	find=`ps | grep 'ubusd' | grep -v 'grep' | awk '{print $1}' | wc -l`
	if [ "$find" = "1" ]
	then
		pid=`ps | grep 'ubusd' | grep -v 'grep' | awk '{print $1}'`
		chrt -r -p 99 $pid
	fi
}

stop() {
	service_stop /sbin/ubusd
}
