#!/bin/sh

usage() {
	echo "getmac <wl1 | wl0 | eth | *>"
	echo "example: getmac"
	echo "         getmac eth"
	echo "         getmac wl0"
	echo "         getmac wl1"
}

ethadr=`hexdump -C /dev/mtd3 -s 40 -n 6 | awk 'NR<2 {print $2":"$3":"$4":"$5":"$6":"$7}'`
wl1adr=`hexdump -C /dev/mtd3 -s 4 -n 6 | awk 'NR<2 {print $2":"$3":"$4":"$5":"$6":"$7}'`
wl0adr=`hexdump -C /dev/mtd3 -s 32772 -n 6 | awk 'NR<2 {print $2":"$3":"$4":"$5":"$6":"$7}'`

case $1 in
	-h)
	usage
	;;
	wl0)
	echo "$wl0adr"
	;;
	wl1)
	echo "$wl1adr"
	;;
	eth)
	echo "$ethadr"
	;;
	*)
	echo "$ethadr,$wl1adr,$wl0adr"
	;;
esac



