#!/bin/sh

if [ $# -eq 0 ]; then
	echo "wps [commands] [parameters]"
	echo "	pbc"
	echo "	status"
	echo "	stamac"
fi

case $1 in
	"pbc")
		iwpriv wl0 set WscConfMode=7
		iwpriv wl0 set WscMode=2
		iwpriv wl0 set WscGetConf=1
		iwpriv wl1 set WscConfMode=7
		iwpriv wl1 set WscMode=2
		iwpriv wl1 set WscGetConf=1
		;;
	*) echo "Parameter $1 is not supported";;
esac
