#!/bin/sh
. /lib/functions.sh
. /lib/functions/network.sh

export LANG=C
usage(){
	echo "USAGE: $0 [timeout] [WAN] [pppoe dhcp|pppoe|dhcp]"
}

timeout="$1"
test -z "$timeout" && timeout=2
let timeout=$timeout+1-1 2>/dev/null
test $? -ne 0 -a "$timeout" != '0' && timeout=2
test $timeout -le 0 && timeout=2

nic="$2"
[ $nic == "WAN" ] && nic="wan"
nic="${nic:-wan}"
network_get_physdev realnic "$nic"
realnic="${realnic:-eth0.2}"
config_load misc
config_get wan_link_op switchop wan_connect
eval "$wan_link_op"
if [ $? -eq 0 ]
then
    nicres="LINK=YES"
else
    nicres="LINK=NO"
fi

echo "$nicres"

tobedetect="$3 $4"
if [ "$tobedetect" = ' ' ]
	then
	tobedetect='pppoe dhcp'
fi

for oncheck in $tobedetect
do
	case "$oncheck" in
		pppoe|PPPOE)
			#check PPPOE
		        runt $timeout /usr/sbin/pppoe-discovery -I $realnic >/dev/null 2>&1
			if [ $? -eq 0 ]
				then
				echo "PPPOE=YES"
			else
				echo "PPPOE=NO"
			fi
			;;
		dhcp|DHCP)
			#check dhcp
			udhcpc -n -q -s /bin/true -t $timeout -T 1 -i $realnic >/dev/null 2>&1
			if [ $? -eq 0 ]
				then
				echo "DHCP=YES"
			else
				echo "DHCP=NO"
			fi
			;;
		*)
			echo "$oncheck=UNKNOW"
			;;
	esac
done
exit 0
#
